version: '3.7'
 
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - /mnt/data/mysql:/var/lib/mysql

  proxysql:
    image: proxysql:2.0.8-local
    container_name: proxysql
    build: ./proxysql
    depends_on:
      - mysql
    ports:
      - "3307:3306"
      - "6032:6032"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
 
